CREATE TABLE STUDENT_TBL(
    STUDENT_ID VARCHAR2(30) PRIMARY KEY,
    STUDENT_PW VARCHAR2(30) NOT NULL,
    STUDENT_NAME VARCHAR2(20) NOT NULL,
    STUDENT_EMAIL VARCHAR2(30),
    STUDENT_PHONE VARCHAR2(13),
    STUDENT_ADDR VARCHAR2(80),
    GENDER VARCHAR2(3) CHECK ( GENDER IN('F','M') ),
    STUDENT_DATE DATE DEFAULT SYSDATE
);
INSERT INTO STUDENT_TBL 
VALUES('khuser01','pass01','일용자','khuser01@naver.com','01034332212', '서울시 중구', 'M', DEFAULT);
COMMIT;
SELECT*FROM STUDENT_TBL;


CREATE TABLE MEMBER_TBL (
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(40), 
    MEMBER_PHONE VARCHAR2(20),
    MEMBER_ADDRESS VARCHAR2(200), 
    MEMBER_GENDER CHAR(1) CHECK(MEMBER_GENDER IN('M','F')),
    MEMBER_HOBBY VARCHAR2(400),
    MEMBER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);